name: mbtech
favicon: null
layout_spectrum: 0.9473363244906068
typography_spectrum: 0.37999017513357103
title: mb technologies
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4735502186231315
  lightness: 0.05345983547158539
  saturation: 0.8615148975513875
  rhythmicContrast: 0.0621935420203954
purpose: []
